project:
  jwt:
    secret: "Z0lMpWVCnqMtTZi4m444meS08MOz5uB0vW9yYXVmdWZ0ZXV5a2xzcWw="

gemini:
  api:
    key: AIzaSyCmVQrQfuaXUVL38FxEvql4rGBpl_4KWHE
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: fake-client-id
            client-secret: fake-secret
            scope: read:user, user:email

  data:
    mongodb:
      uri: mongodb+srv://maanavchellani_db_user:4JeIAcQcphRFpoLU@cluster0.aybiidh.mongodb.net/?appName=Cluster0
      database: journal_db
      auto-index-creation: true

    redis:
      # We break this down into separate fields to ensure Spring Boot parses it correctly
      host: redis-12961.c263.us-east-1-2.ec2.cloud.redislabs.com
      port: 12961
      password: Z0lMpWVCnqMtTZi4m444meS08MOz5uB0
      username: default
      timeout: 60000ms # Increased timeout for cloud connections

  mail:
    host: smtp.gmail.com
    port: 587
    username: maanav.chellani@gmail.com
    password: wynagufteuyklsql
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true